### ISSUE TITLE
The domain "batterylow.me" is not "https".

### ISSUE THREAD

**Issue by siko1056** [me-ydv-5/me-ydv-5.github.io#2]
Dear Sahil,

When accessing your blog, I get directed to https://batterylow.me/gsoc2018/week2, which results in an ugly privacy error using chrome.  Maybe you just type "http" there:

https://github.com/me-ydv-5/me-ydv-5.github.io/blob/bd4950ee6b8a5d3d4efb8638abc17eab217db89b/_config.yml#L18

Or get a certificate from [Let's Encrypt](https://letsencrypt.org/) or alike.

Thanks for caring.
Kai

**Comment by me-ydv-5** [comment]
Hi Kai
Unfortunately, Let's Encrypt do not have support for domains issued through namecheap.com. However, I've requested a front-end SSL certificate from cloudflare.com so that a user can get secured connection to the site even if the connection remains insecure between cloudflare and Github itself. I'll wait for around 48 hours for the certificate to be issued. If nothing happens, I'll just remove the CNAME record batterylow.me from my github pages and we'll be good to go with https://me-ydv-5.github.io .

**Comment by me-ydv-5** [comment]
The issue seems to have been resolved! Now the site is secured through SSL protocol
